version: '3.3'

services:

  database:
    container_name: ${APP_NAME}-database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql

  php:
    container_name: ${APP_NAME}-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
    depends_on:
      - database

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:1.20-alpine
    ports:
      - '7000:80'
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: ${APP_NAME}-pma
    links:
      - database
    environment:
      PMA_HOST: ${APP_NAME}-database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

volumes:
    db_data: ~