sf-install-5.4: ## Installation de la version 5.4 de Symfony
	$(EXEC_SYMFONY) symfony new . --version=5.4

sf-install-6.0: ## Installation de la version 6.0 de Symfony
	$(EXEC_SYMFONY) symfony new . --version=6.0
