sf-install-6.3: ## Installation de la version 6.3 de Symfony
	$(EXEC_SYMFONY) symfony new . --version="6.3.*" --webapp

sf-install-6.4: ## Installation de la version 6.4 de Symfony
	$(EXEC_SYMFONY) symfony new . --version="6.4.*@dev" --webapp

sf-check-requirements: # Vérification des prérequis
	$(EXEC_SYMFONY) symfony check:requirements